services:
  iptv:
    image: yexundao/iptv:latest
    container_name: iptv
    restart: always
    volumes:
      - ./sources:/workspace/sources
      - ./output:/workspace/output
    ports:
      - "15123:15123"
    environment:
      SOURCE_DESC: "高质量 → 本地源"
      CRON_SCHEDULE: "0 */6 * * *"            # 每6小时重启一次